### ISSUE TITLE
"Choose File" button will not select .yaml files

### ISSUE THREAD

**Issue by kiranetph** [getgrav/grav-plugin-license-manager#5]
![image](https://user-images.githubusercontent.com/15226809/102349743-c37d7200-3fde-11eb-8158-022b4f66bfb1.jpeg)

Safari V14.0.2

**Comment by w00fz** [comment]
Is the issue that the xml extension cannot be picked from the finder view or does it not open the finder view at all?

Also, curious if you tried dragging the file on top of the field? Does that work?

**Comment by kiranetph** [comment]
Dragging works.
The finder view opens, but the licenses.yaml can not be picked.
![image](https://user-images.githubusercontent.com/15226809/102382422-69dc6e00-4005-11eb-8f82-357858d8f737.jpeg)

**Comment by w00fz** [comment]
Great, thanks for the info.

**Comment by w00fz** [comment]
This is now resolved in 1.0.1.

Cheers
